DROP INDEX IF EXISTS "ApiKey_user_id_key";

ALTER TABLE "ApiKey"
  ADD COLUMN IF NOT EXISTS "key_hint" TEXT NOT NULL DEFAULT 'sms_legacy…',
  ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT 'API key',
  ADD COLUMN IF NOT EXISTS "usage_count" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "last_used_at" TIMESTAMP(3);
